replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/project-testing/backend-api
  tag: 1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

route:
  enabled: true
  hostname: backendapi.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}